# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    main.yml                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: vhacman <vhacman@student.42roma.it>        +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2025/03/23 15:04:13 by vhacman           #+#    #+#              #
#    Updated: 2025/03/23 15:04:13 by vhacman          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

name: Libft CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Compile with Makefile
      run: make
